export interface Product {
  id: number
  name: string
  category: string
  producer: string
  vendorId: string
  location: string
  country: string
  description: string
  seller?: string // Added to fix type compatibility
  fullDescription: string
  price: string
  minOrder: string
  rating: number
  reviews: number
  image: string
  verified: boolean
  slug: string
  packaging: string
  packagingSize: string
  contactMethod?: string
  contactInfo?: string
  specifications?: {
    label: string
    value: string
  }[]
}

export const allProducts: Product[] = [
  {
    id: 21,
    name: "Azúcar de Caña Refinada",
    category: "Caña de azúcar",
    producer: "Ingenio San Miguel",
    vendorId: "vendor_021",
    location: "San Miguel, El Salvador",
    country: "El Salvador",
    description: "Azúcar de caña refinada, calidad premium para exportación",
    fullDescription:
      "Azúcar de caña 100% natural refinada con procesos de alta tecnología. Color blanco brillante, textura fina y cristalina. Empacada en sacos de 50kg en instalaciones con certificación sanitaria internacional. Ideal para industria alimentaria, panadería, repostería y exportación.",
    price: "$0.65/kg",
    minOrder: "1000 kg",
    rating: 4.9,
    reviews: 234,
    image: "/azucar-cana-refinada-sacos.jpg",
    verified: true,
    slug: "azucar-cana-refinada",
    packaging: "Sacos",
    packagingSize: "50 kg",
    specifications: [
      { label: "Tipo", value: "Refinada premium" },
      { label: "Origen", value: "San Miguel, El Salvador" },
      { label: "Pureza", value: "99.8%" },
      { label: "Color", value: "Blanco brillante" },
      { label: "Certificación", value: "Internacional" },
      { label: "Aplicación", value: "Industrial y exportación" },
    ],
  },
  {
    id: 19,
    name: "Café Premium Salvadoreño",
    category: "Café",
    producer: "Finca Montaña Brava",
    vendorId: "vendor_019",
    location: "Chalatenango, El Salvador",
    country: "El Salvador",
    description: "Café gourmet de altura, aroma floral y frutal",
    fullDescription:
      "Café arábica premium de altura cultivado en volcán Santa Ana a 1300 metros. Procesamiento experimental con fermentación natural. Aroma floral intenso con notas de frutas rojas y cacao.",
    price: "$7.50/kg",
    minOrder: "25 kg",
    rating: 4.9,
    reviews: 156,
    image: "/cafe-premium-salvadoreno.jpg",
    verified: true,
    slug: "cafe-premium-salvadoreno",
    packaging: "Bolsas",
    packagingSize: "1 kg",
    specifications: [
      { label: "Variedad", value: "Arábica Premium" },
      { label: "Altitud", value: "1300 metros" },
      { label: "Proceso", value: "Fermentación natural" },
      { label: "Notas", value: "Floral, frutas rojas, cacao" },
    ],
  },
  {
    id: 20,
    name: "Aguacate Mexicano",
    category: "Frutas",
    producer: "Aguacatales de Michoacán",
    vendorId: "vendor_020",
    location: "Michoacán, México",
    country: "México",
    description: "Aguacate hass, cremoso y de excelente sabor",
    fullDescription:
      "Aguacate hass de Michoacán, la región productora más importante de México. Cremoso, con excelente sabor y contenido de grasas monoinsaturadas. Cosechado en el punto óptimo de madurez para exportación.",
    price: "$2.80/kg",
    minOrder: "600 kg",
    rating: 4.9,
    reviews: 312,
    image: "/aguacate-mexicano-hass.jpg",
    verified: true,
    slug: "aguacate-mexicano",
    packaging: "Cajas",
    packagingSize: "50 kg",
    specifications: [
      { label: "Variedad", value: "Hass" },
      { label: "Origen", value: "Michoacán, México" },
      { label: "Textura", value: "Cremoso" },
      { label: "Cosecha", value: "Punto óptimo de madurez" },
    ],
  },
  {
    id: 17,
    name: "Algodón en Rama Premium",
    category: "Algodón",
    producer: "Algodones de Oriente",
    vendorId: "vendor_017",
    location: "San Miguel, El Salvador",
    country: "El Salvador",
    description: "Algodón de fibra larga, limpieza mecánica",
    fullDescription:
      "Algodón premium en rama de fibra larga, procesado con limpieza mecánica de última tecnología. Libre de impurezas, listo para desfibrado industrial.",
    price: "$3.00/kg",
    minOrder: "500 kg",
    rating: 4.8,
    reviews: 145,
    image: "/algodon-rama-premium-cultivo.jpg",
    verified: true,
    slug: "algodon-rama",
    packaging: "Pacas",
    packagingSize: "250 kg",
    specifications: [
      { label: "Tipo", value: "Fibra larga" },
      { label: "Origen", value: "San Miguel, El Salvador" },
      { label: "Procesamiento", value: "Limpieza mecánica" },
      { label: "Pureza", value: "Alta" },
    ],
  },
  {
    id: 18,
    name: "Algodón Desmotado",
    category: "Algodón",
    producer: "Procesadora de Algodón",
    vendorId: "vendor_018",
    location: "Usulután, El Salvador",
    country: "El Salvador",
    description: "Algodón listo para procesamiento textil",
    fullDescription:
      "Algodón completamente desmotado y acondicionado para procesamiento textil industrial. Listo para hilandería, tejeduría y fabricación de textiles de alta calidad.",
    price: "$3.80/kg",
    minOrder: "1000 kg",
    rating: 4.5,
    reviews: 67,
    image: "/algodon-desmotado-procesamiento-textil.jpg",
    verified: false,
    slug: "algodon-desmotado",
    packaging: "Pacas",
    packagingSize: "300 kg",
    specifications: [
      { label: "Tipo", value: "Desmotado" },
      { label: "Origen", value: "Usulután, El Salvador" },
      { label: "Aplicación", value: "Textil industrial" },
      { label: "Acondicionamiento", value: "Completo" },
    ],
  },
  {
    id: 22,
    name: "Alfalfa Pellet",
    category: "Forraje",
    producer: "Forrajes Premium Argentina",
    vendorId: "vendor_022",
    location: "Buenos Aires, Argentina",
    country: "Argentina",
    description: "Alfalfa pellet de alta calidad, procesada con tecnología de punta",
    fullDescription:
      "Alfalfa pellet premium de origen argentino, procesada con tecnología de última generación. Alto contenido proteico (18-20%), ideal para alimentación de ganado lechero, bovino de carne, equinos y ovinos. Densidad óptima para transporte y almacenamiento. Empacada en bolsas de 25kg con sellado hermético.",
    price: "$0.35/kg",
    minOrder: "1000 kg",
    rating: 4.9,
    reviews: 187,
    image: "/alfalfa-pellet-forraje.jpg",
    verified: true,
    slug: "alfalfa-pellet",
    packaging: "Bolsas",
    packagingSize: "25 kg",
    specifications: [
      { label: "Origen", value: "Buenos Aires, Argentina" },
      { label: "Proteína", value: "18-20%" },
      { label: "Formato", value: "Pellet compactado" },
      { label: "Aplicación", value: "Alimentación ganadera" },
      { label: "Humedad", value: "10% máx." },
    ],
  },
  {
    id: 23,
    name: "Alfalfa Cubes",
    category: "Forraje",
    producer: "Forrajes Premium Argentina",
    vendorId: "vendor_023",
    location: "Córdoba, Argentina",
    country: "Argentina",
    description: "Alfalfa en cubos, fácil manejo y dosificación",
    fullDescription:
      "Alfalfa argentina en formato de cubos compactados, ideal para alimentación equina y bovina. Excelente palatabilidad y digestibilidad. Formato cube facilita el manejo, dosificación y reduce desperdicio. Rico en fibra y proteínas, bajo en polvo. Empacado en sacos de 20kg.",
    price: "$0.38/kg",
    minOrder: "800 kg",
    rating: 4.8,
    reviews: 143,
    image: "/alfalfa-cubes-forraje-compactado.jpg",
    verified: true,
    slug: "alfalfa-cubes",
    packaging: "Sacos",
    packagingSize: "20 kg",
    specifications: [
      { label: "Origen", value: "Córdoba, Argentina" },
      { label: "Formato", value: "Cubos compactados" },
      { label: "Proteína", value: "17-19%" },
      { label: "Fibra", value: "Alta calidad" },
      { label: "Polvo", value: "Mínimo" },
    ],
  },
  {
    id: 24,
    name: "Semillas de Chía",
    category: "Semillas",
    producer: "Superfoods del Sur",
    vendorId: "vendor_024",
    location: "Cochabamba, Bolivia",
    country: "Bolivia",
    description: "Semillas de chía orgánicas, alto contenido de omega-3",
    fullDescription:
      "Semillas de chía orgánicas certificadas, cultivadas en las tierras altas de Bolivia. Superalimento con alto contenido de omega-3, fibra, proteínas y antioxidantes. Color negro uniforme, libre de impurezas. Ideal para exportación a mercados de alimentos saludables y suplementos nutricionales. Empacada en bolsas de 25kg con sellado al vacío.",
    price: "$4.50/kg",
    minOrder: "200 kg",
    rating: 4.9,
    reviews: 265,
    image: "/semillas-chia-organicas-superalimento.jpg",
    verified: true,
    slug: "semillas-chia",
    packaging: "Bolsas",
    packagingSize: "25 kg",
    specifications: [
      { label: "Certificación", value: "Orgánica" },
      { label: "Origen", value: "Cochabamba, Bolivia" },
      { label: "Omega-3", value: "Alto contenido" },
      { label: "Pureza", value: "99.9%" },
      { label: "Color", value: "Negro uniforme" },
      { label: "Aplicación", value: "Alimentación saludable" },
    ],
  },
  {
    id: 25,
    name: "Semilla Entera de Algodón",
    category: "Semillas",
    producer: "Algodonera Uruguay",
    vendorId: "vendor_025",
    location: "Paysandú, Uruguay",
    country: "Uruguay",
    description: "Semilla entera de algodón para alimentación animal y extracción de aceite",
    fullDescription:
      "Semilla entera de algodón de origen uruguayo, subproducto de alta calidad. Rica en proteínas (23-25%) y aceite (18-20%), ideal para alimentación de ganado lechero y bovino de engorde. También utilizada para extracción de aceite comestible y producción de harina proteica. Libre de gossypol libre en niveles seguros. Empacada en sacos de 40kg.",
    price: "$0.28/kg",
    minOrder: "2000 kg",
    rating: 4.7,
    reviews: 98,
    image: "/semilla-algodon-entera-alimentacion-animal.jpg",
    verified: true,
    slug: "semilla-algodon",
    packaging: "Sacos",
    packagingSize: "40 kg",
    specifications: [
      { label: "Origen", value: "Paysandú, Uruguay" },
      { label: "Proteína", value: "23-25%" },
      { label: "Aceite", value: "18-20%" },
      { label: "Aplicación", value: "Alimentación animal y extracción" },
      { label: "Gossypol libre", value: "Niveles seguros" },
      { label: "Formato", value: "Semilla entera" },
    ],
  },
  {
    id: 26,
    name: "Insecticida Cipermetrina 25%",
    category: "Plaguicidas",
    producer: "AgroQuímica Central",
    vendorId: "vendor_026",
    location: "Guatemala City, Guatemala",
    country: "Guatemala",
    description: "Insecticida piretroide de amplio espectro para control de plagas",
    fullDescription:
      "Insecticida de contacto y acción residual basado en cipermetrina al 25% EC. Eficaz contra lepidópteros, coleópteros, hemípteros y ácaros en cultivos de maíz, algodón, soya, hortalizas y frutales. Acción temprana. Formulación concentrada emulsionable de fácil dilución y aplicación. Período de carencia: 7-15 días según cultivo. Empacado en bidones de 20 litros con certificación fitosanitaria internacional.",
    price: "$12.50/litro",
    minOrder: "100 litros",
    rating: 4.7,
    reviews: 89,
    image: "/insecticida-cipermetrina-bidon.jpg",
    verified: true,
    slug: "insecticida-cipermetrina",
    packaging: "Bidones",
    packagingSize: "20 L",
    specifications: [
      { label: "Ingrediente activo", value: "Cipermetrina 25% EC" },
      { label: "Tipo", value: "Insecticida piretroide" },
      { label: "Modo de acción", value: "Contacto y residual" },
      { label: "Certificación", value: "Fitosanitaria internacional" },
      { label: "Período carencia", value: "7-15 días" },
      { label: "Aplicación", value: "Cereales, algodón, hortalizas, frutales" },
    ],
  },
  {
    id: 27,
    name: "Fungicida Mancozeb 80% WP",
    category: "Plaguicidas",
    producer: "Protección Agrícola S.A.",
    vendorId: "vendor_027",
    location: "San José, Costa Rica",
    country: "Costa Rica",
    description: "Fungicida preventivo de amplio espectro contra enfermedades foliares",
    fullDescription:
      "Fungicida de contacto preventivo basado en Mancozeb 80% WP (polvo mojable). Altamente eficaz contra mildiu, antracnosis, cercosporiosis, tizón y otras enfermedades fungosas en papa, tomate, vid, café, banano y ornamentales. Formulación en polvo de fácil suspensión y aplicación foliar. Compatible con la mayoría de insecticidas y fertilizantes foliares. Empacado en bolsas hidrosolubles de 1kg dentro de cajas de 20kg.",
    price: "$8.75/kg",
    minOrder: "200 kg",
    rating: 4.8,
    reviews: 134,
    image: "/fungicida-mancozeb-bolsas.jpg",
    verified: true,
    slug: "fungicida-mancozeb",
    packaging: "Cajas",
    packagingSize: "20 kg",
    specifications: [
      { label: "Ingrediente activo", value: "Mancozeb 80% WP" },
      { label: "Tipo", value: "Fungicida preventivo de contacto" },
      { label: "Modo de acción", value: "Multi-sitio" },
      { label: "Certificación", value: "Registro sanitario vigente" },
      { label: "Compatibilidad", value: "Alta con otros agroquímicos" },
      { label: "Aplicación", value: "Papa, tomate, café, banano, vid" },
    ],
  },
  {
    id: 28,
    name: "Fertilizante NPK 15-15-15",
    category: "Fertilizantes",
    producer: "Nutrientes del Campo",
    vendorId: "vendor_028",
    location: "León, Nicaragua",
    country: "Nicaragua",
    description: "Fertilizante completo balanceado para todo tipo de cultivos",
    fullDescription:
      "Fertilizante granulado NPK 15-15-15 de formulación balanceada, ideal para crecimiento vegetativo y producción. Contiene nitrógeno, fósforo y potasio en proporciones iguales, más micronutrientes esenciales (zinc, boro, magnesio). Excelente para cultivos de ciclo corto y largo, hortalizas, cereales, leguminosas y frutales. Granulometría uniforme para aplicación manual o mecanizada. Empacado en sacos de 50kg con recubrimiento resistente a humedad.",
    price: "$0.52/kg",
    minOrder: "2000 kg",
    rating: 4.6,
    reviews: 156,
    image: "/fertilizante-npk-15-15-15-sacos.jpg",
    verified: true,
    slug: "fertilizante-npk-15-15-15",
    packaging: "Sacos",
    packagingSize: "50 kg",
    specifications: [
      { label: "Composición", value: "15% N - 15% P₂O₅ - 15% K₂O" },
      { label: "Tipo", value: "Granulado balanceado" },
      { label: "Micronutrientes", value: "Zn, B, Mg" },
      { label: "Aplicación", value: "Universal: cereales, hortalizas, frutales" },
      { label: "Granulometría", value: "2-4 mm" },
      { label: "Solubilidad", value: "Media-alta" },
    ],
  },
  {
    id: 29,
    name: "Urea Agrícola 46% N",
    category: "Fertilizantes",
    producer: "Fertilizantes Industriales",
    vendorId: "vendor_029",
    location: "Managua, Nicaragua",
    country: "Nicaragua",
    description: "Fuente concentrada de nitrógeno para máximo rendimiento",
    fullDescription:
      "Urea granulada de grado agrícola con 46% de nitrógeno total, la fuente más concentrada de N disponible. Fertilizante nitrogenado de liberación rápida, ideal para aplicaciones en cobertura durante etapas de máxima demanda. Excelente para maíz, arroz, trigo, caña de azúcar y pastos. Gránulos uniformes de 2-4mm que facilitan distribución mecánica homogénea. Empaque en sacos de 50kg con tratamiento antiapelmazante.",
    price: "$0.48/kg",
    minOrder: "5000 kg",
    rating: 4.9,
    reviews: 203,
    image: "/urea-agricola-46-sacos.jpg",
    verified: true,
    slug: "urea-46",
    packaging: "Sacos",
    packagingSize: "50 kg",
    specifications: [
      { label: "Nitrógeno total", value: "46% mín." },
      { label: "Tipo", value: "Urea granulada" },
      { label: "Liberación", value: "Rápida" },
      { label: "Aplicación", value: "Maíz, arroz, caña, pastos" },
      { label: "Granulometría", value: "2-4 mm" },
      { label: "Biuret", value: "< 1.2%" },
    ],
  },
  {
    id: 30,
    name: "Fertilizante Foliar Completo",
    category: "Fertilizantes",
    producer: "Soluciones Nutricionales Avanzadas",
    vendorId: "vendor_030",
    location: "San Salvador, El Salvador",
    country: "El Salvador",
    description: "Nutrición foliar líquida con macro y micronutrientes quelatados",
    fullDescription:
      "Fertilizante foliar líquido de alta concentración con macro y micronutrientes totalmente quelatados para máxima absorción. Contiene NPK + Ca, Mg, S, Fe, Mn, Zn, Cu, B, Mo en formas queladas de alta disponibilidad. pH balanceado, baja salinidad, compatible con la mayoría de pesticidas. Resultados visibles en 48-72 horas. Ideal para corrección rápida de deficiencias, estrés hídrico, heladas y recuperación post-trasplante. Bidones de 20 litros.",
    price: "$15.80/litro",
    minOrder: "100 litros",
    rating: 4.8,
    reviews: 178,
    image: "/fertilizante-foliar-completo-bidon.jpg",
    verified: true,
    slug: "fertilizante-foliar",
    packaging: "Bidones",
    packagingSize: "20 L",
    specifications: [
      { label: "NPK", value: "12-6-12 + micronutrientes" },
      { label: "Tipo", value: "Líquido quelatado" },
      { label: "Absorción", value: "Rápida (48-72h)" },
      { label: "pH", value: "5.5-6.5" },
      { label: "Compatibilidad", value: "Alta con pesticidas" },
      { label: "Aplicación", value: "Foliar universal" },
    ],
  },
  {
    id: 31,
    name: "Herbicida Glifosato 48% SL",
    category: "Herbicidas",
    producer: "Control de Malezas Centroamérica",
    vendorId: "vendor_031",
    location: "Tegucigalpa, Honduras",
    country: "Honduras",
    description: "Herbicida sistémico post-emergente no selectivo de amplio espectro",
    fullDescription:
      "Herbicida sistémico post-emergente basado en glifosato sal isopropilamina al 48% SL (solución concentrada). Control total de malezas anuales y perennes, gramíneas y hoja ancha. Absorción foliar y traslocación a raíces y rizomas. Inactivo en el suelo, permite siembra inmediata. Ideal para barbechos, limpieza pre-siembra, control entre hileras de cultivos perennes, y mantenimiento de áreas no cultivadas. Efectos visibles en 7-15 días. Bidones de 20 litros con certificación ambiental.",
    price: "$6.50/litro",
    minOrder: "200 litros",
    rating: 4.7,
    reviews: 267,
    image: "/herbicida-glifosato-48-bidon.jpg",
    verified: true,
    slug: "herbicida-glifosato",
    packaging: "Bidones",
    packagingSize: "20 L",
    specifications: [
      { label: "Ingrediente activo", value: "Glifosato 48% SL" },
      { label: "Tipo", value: "Sistémico post-emergente no selectivo" },
      { label: "Modo de acción", value: "Inhibidor EPSPS" },
      { label: "Efectividad", value: "7-15 días" },
      { label: "Residualidad", value: "Nula en suelo" },
      { label: "Aplicación", value: "Barbechos, pre-siembra, cultivos perennes" },
    ],
  },
  {
    id: 32,
    name: "Herbicida Atrazina 50% SC",
    category: "Herbicidas",
    producer: "AgroDefensa Premium",
    vendorId: "vendor_032",
    location: "Guatemala City, Guatemala",
    country: "Guatemala",
    description: "Herbicida selectivo pre y post-emergente para maíz y sorgo",
    fullDescription:
      "Herbicida selectivo basado en Atrazina 50% SC (suspensión concentrada). Control de malezas de hoja ancha y algunas gramíneas en cultivos de maíz, sorgo y caña de azúcar. Acción pre-emergente y post-emergente temprana. Absorción radicular y foliar con efecto residual de 60-90 días. Formulación en suspensión de alta estabilidad y fácil mezclado. Compatible con otros herbicidas para control de espectro ampliado. Bidones de 20 litros con registro sanitario vigente.",
    price: "$7.25/litro",
    minOrder: "150 litros",
    rating: 4.6,
    reviews: 142,
    image: "/herbicida-atrazina-50-bidon.jpg",
    verified: true,
    slug: "herbicida-atrazina",
    packaging: "Bidones",
    packagingSize: "20 L",
    specifications: [
      { label: "Ingrediente activo", value: "Atrazina 50% SC" },
      { label: "Tipo", value: "Selectivo pre y post-emergente" },
      { label: "Modo de acción", value: "Inhibidor fotosíntesis (PSII)" },
      { label: "Residualidad", value: "60-90 días" },
      { label: "Selectividad", value: "Maíz, sorgo, caña de azúcar" },
      { label: "Compatibilidad", value: "Alta con otros herbicidas" },
    ],
  },
  {
    id: 16,
    name: "Caña de Azúcar Fresca",
    category: "Caña de azúcar",
    producer: "Ingenio Santa Rosa",
    vendorId: "vendor_016",
    location: "Sonsonate, El Salvador",
    country: "El Salvador",
    description: "Caña de azúcar fresca, cortada diariamente",
    fullDescription:
      "Caña de azúcar fresca cortada diariamente en el punto óptimo de madurez. Alto contenido de sacarosa, perfecto para ingenios azucareros y procesamiento artesanal.",
    price: "$0.12/kg",
    minOrder: "5000 kg",
    rating: 4.7,
    reviews: 78,
    image: "/cana-azucar-fresca-cultivo.jpg",
    verified: true,
    slug: "cana-azucar",
    packaging: "A granel",
    packagingSize: "Variado",
    specifications: [
      { label: "Origen", value: "Sonsonate, El Salvador" },
      { label: "Cosecha", value: "Diaria" },
      { label: "Madurez", value: "Óptima" },
      { label: "Sacarosa", value: "Alto contenido" },
    ],
  },
  {
    id: 1,
    name: "Plátano Premium",
    category: "Frutas",
    producer: "Don Pedro López",
    vendorId: "vendor_001",
    location: "Sonsonate, El Salvador",
    country: "El Salvador",
    description: "Plátano fresco de calidad premium, cosechado hace 2 días",
    fullDescription:
      "Plátano fresco de calidad premium cultivado en las mejores condiciones. Cosechado hace 2 días en el punto óptimo de madurez. Perfecto para mercados internacionales con certificaciones de calidad.",
    price: "$0.45/kg",
    minOrder: "500 kg",
    rating: 4.8,
    reviews: 124,
    image: "/platano-premium-cajas-empaque.jpg",
    verified: true,
    slug: "platano-premium",
    packaging: "Cajas",
    packagingSize: "40 kg",
    specifications: [
      { label: "Origen", value: "Sonsonate, El Salvador" },
      { label: "Cosecha", value: "Reciente (2 días)" },
      { label: "Madurez", value: "Óptima" },
      { label: "Certificación", value: "Estándar internacional" },
    ],
  },
  {
    id: 2,
    name: "Piña Madura",
    category: "Frutas",
    producer: "Finca Las Flores",
    vendorId: "vendor_002",
    location: "Cuscatlán, El Salvador",
    country: "El Salvador",
    description: "Piña madura lista para exportación, sin químicos",
    fullDescription:
      "Piña tropical de excelente calidad, cultivada sin químicos sintéticos. Madura naturalmente en el árbol para máximo sabor y contenido de azúcar. Lista para exportación inmediata.",
    price: "$0.70/kg",
    minOrder: "1000 kg",
    rating: 4.9,
    reviews: 98,
    image: "/pina-madura-cajas-empaque-exportacion.jpg",
    verified: true,
    slug: "pina-madura",
    packaging: "Cajas",
    packagingSize: "50 kg",
    specifications: [
      { label: "Origen", value: "Cuscatlán, El Salvador" },
      { label: "Cultivo", value: "Sin químicos sintéticos" },
      { label: "Madurez", value: "Natural" },
      { label: "Estado", value: "Listo para exportar" },
    ],
  },
  {
    id: 3,
    name: "Mango Ataulfo",
    category: "Frutas",
    producer: "Agrícola Santa Bárbara",
    vendorId: "vendor_003",
    location: "Santa Bárbara, Honduras",
    country: "Honduras",
    description: "Mango ataulfo y tommy, dulce y jugoso",
    fullDescription:
      "Variedades premium de mango: ataulfo y tommy. Dulce, jugoso y con aroma intenso. Cultivado en las mejores condiciones climáticas de Honduras con técnicas tradicionales.",
    price: "$1.10/kg",
    minOrder: "800 kg",
    rating: 4.7,
    reviews: 156,
    image: "/mango-ataulfo-cajas-empaque-exportacion.jpg",
    verified: true,
    slug: "mango-ataulfo",
    packaging: "Cajas",
    packagingSize: "45 kg",
    specifications: [
      { label: "Variedades", value: "Ataulfo y Tommy" },
      { label: "Origen", value: "Santa Bárbara, Honduras" },
      { label: "Sabor", value: "Dulce e intenso" },
      { label: "Proceso", value: "Técnicas tradicionales" },
    ],
  },
  {
    id: 4,
    name: "Papaya Roja",
    category: "Frutas",
    producer: "Huertos del Trópico",
    vendorId: "vendor_004",
    location: "La Paz, El Salvador",
    country: "El Salvador",
    description: "Papaya roja dulce, perfecta para mercados internacionales",
    fullDescription:
      "Papaya roja de pulpa dulce y aromática. Ideal para mercados internacionales con excelente presentación y sabor. Cosechada en el punto óptimo de madurez.",
    price: "$0.65/kg",
    minOrder: "600 kg",
    rating: 4.6,
    reviews: 87,
    image: "/papaya-roja-cajas-empaque-exportacion.jpg",
    verified: false,
    slug: "papaya-roja",
    packaging: "Cajas",
    packagingSize: "38 kg",
    specifications: [
      { label: "Origen", value: "La Paz, El Salvador" },
      { label: "Tipo", value: "Papaya roja" },
      { label: "Pulpa", value: "Dulce y aromática" },
      { label: "Presentación", value: "Excelente" },
    ],
  },
  {
    id: 5,
    name: "Zanahoria Orgánica",
    category: "Verduras",
    producer: "Cultivos Sostenibles SV",
    vendorId: "vendor_005",
    location: "Cabañas, El Salvador",
    country: "El Salvador",
    description: "Zanahoria fresca orgánica, sin pesticidas",
    fullDescription:
      "Zanahoria completamente orgánica certificada, cultivada sin pesticidas ni productos químicos sintéticos. Fresca, crujiente y con excelente contenido nutricional.",
    price: "$0.50/kg",
    minOrder: "400 kg",
    rating: 4.9,
    reviews: 203,
    image: "/zanahoria-organica-bolsas-empaque.jpg",
    verified: true,
    slug: "zanahoria-organica",
    packaging: "Bolsas",
    packagingSize: "25 kg",
    specifications: [
      { label: "Certificación", value: "Orgánica" },
      { label: "Origen", value: "Cabañas, El Salvador" },
      { label: "Pesticidas", value: "Ninguno" },
      { label: "Textura", value: "Crujiente" },
    ],
  },
  {
    id: 6,
    name: "Brócoli Premium",
    category: "Verduras",
    producer: "Verde Exportaciones",
    vendorId: "vendor_006",
    location: "Chalatenango, El Salvador",
    country: "El Salvador",
    description: "Brócoli de grado exportación, fresco diariamente",
    fullDescription:
      "Brócoli de grado exportación de máxima calidad. Cosechado diariamente en el punto óptimo de madurez. Certificado para mercados internacionales con estándares sanitarios más exigentes.",
    price: "$1.75/kg",
    minOrder: "300 kg",
    rating: 4.8,
    reviews: 145,
    image: "/brocoli-premium-cajas-empaque-exportacion.jpg",
    verified: true,
    slug: "brocoli-premium",
    packaging: "Cajas",
    packagingSize: "20 kg",
    specifications: [
      { label: "Grado", value: "Exportación" },
      { label: "Origen", value: "Chalatenango, El Salvador" },
      { label: "Cosecha", value: "Diaria" },
      { label: "Certificaciones", value: "Internacionales" },
    ],
  },
  {
    id: 7,
    name: "Tomate Rojo Maduro",
    category: "Verduras",
    producer: "Finca Casa Blanca",
    vendorId: "vendor_007",
    location: "San Vicente, El Salvador",
    country: "El Salvador",
    description: "Tomate rojo maduro, cosecha del día",
    fullDescription:
      "Tomate rojo completamente maduro, cosechado el mismo día. Sabor intenso, aromático y perfecta textura. Ideal para consumo en fresco o procesamiento industrial.",
    price: "$0.75/kg",
    minOrder: "500 kg",
    rating: 4.5,
    reviews: 76,
    image: "/tomate-rojo-cajas-empaque-exportacion.jpg",
    verified: true,
    slug: "tomate-rojo",
    packaging: "Cajas",
    packagingSize: "28 kg",
    specifications: [
      { label: "Madurez", value: "Completa" },
      { label: "Origen", value: "San Vicente, El Salvador" },
      { label: "Cosecha", value: "Del día" },
      { label: "Usos", value: "Fresco e industrial" },
    ],
  },
  {
    id: 8,
    name: "Chile Verde y Rojo",
    category: "Verduras",
    producer: "Picantes del Centro",
    vendorId: "vendor_008",
    location: "Cuscatlán, El Salvador",
    country: "El Salvador",
    description: "Chile verde y rojo fresco, ideal para exportación",
    fullDescription:
      "Chile verde y rojo fresco de excelente calidad. Picante y aromático, ideal para exportación a mercados internacionales. Cultivo bajo estrictos controles de calidad.",
    price: "$2.50/kg",
    minOrder: "250 kg",
    rating: 4.7,
    reviews: 92,
    image: "/chile-verde-rojo-cajas-empaque-exportacion.jpg",
    verified: true,
    slug: "chile-picante",
    packaging: "Cajas",
    packagingSize: "15 kg",
    specifications: [
      { label: "Variedades", value: "Verde y Rojo" },
      { label: "Origen", value: "Cuscatlán, El Salvador" },
      { label: "Nivel Picante", value: "Moderado-Alto" },
      { label: "Control Calidad", value: "Estricto" },
    ],
  },
  {
    id: 9,
    name: "Maíz Amarillo Grado Exportación",
    category: "Cereales",
    producer: "Granos de Oro",
    vendorId: "vendor_009",
    location: "San Miguel, El Salvador",
    country: "El Salvador",
    description: "Maíz amarillo grado exportación, humedad controlada",
    fullDescription:
      "Maíz amarillo certificado de grado exportación. Humedad controlada, libre de plagas y con excelente germinación. Empacado en sacos de 50kg con trazabilidad completa.",
    price: "$0.30/kg",
    minOrder: "2000 kg",
    rating: 4.8,
    reviews: 178,
    image: "/maiz-amarillo-sacos-granel.jpg",
    verified: true,
    slug: "maiz-amarillo",
    packaging: "Sacos",
    packagingSize: "50 kg",
    specifications: [
      { label: "Grado", value: "Exportación" },
      { label: "Origen", value: "San Miguel, El Salvador" },
      { label: "Humedad", value: "Controlada" },
      { label: "Trazabilidad", value: "Completa" },
    ],
  },
  {
    id: 10,
    name: "Arroz Blanco Pulido",
    category: "Cereales",
    producer: "Arrocería Central",
    vendorId: "vendor_010",
    location: "Usulután, El Salvador",
    country: "El Salvador",
    description: "Arroz blanco pulido, empacado en sacos de 50kg",
    fullDescription:
      "Arroz blanco de grano largo, perfectamente pulido y blanqueado. Empacado en sacos de 50kg en instalaciones sanitizadas. Listo para distribución internacional.",
    price: "$0.45/kg",
    minOrder: "1000 kg",
    rating: 4.6,
    reviews: 134,
    image: "/arroz-blanco-sacos-empaque-50kg.jpg",
    verified: true,
    slug: "arroz-blanco",
    packaging: "Sacos",
    packagingSize: "50 kg",
    specifications: [
      { label: "Tipo", value: "Grano largo" },
      { label: "Origen", value: "Usulután, El Salvador" },
      { label: "Presentación", value: "Sacos de 50kg" },
      { label: "Proceso", value: "Pulido y blanqueado" },
    ],
  },
  {
    id: 11,
    name: "Café Arábica de Altura",
    category: "Café",
    producer: "Cafetales de la Altura",
    vendorId: "vendor_011",
    location: "Morazán, El Salvador",
    country: "El Salvador",
    description: "Café de altura grado A, con denominación de origen",
    fullDescription:
      "Café arábica grado A cultivado a más de 1000 metros de altitud. Con denominación de origen protegida. Aroma intenso, sabor complejo y notas de chocolate y caramelo.",
    price: "$5.50/kg",
    minOrder: "50 kg",
    rating: 4.9,
    reviews: 287,
    image: "/cafe-arabica-grano-tostado.jpg",
    verified: true,
    slug: "cafe-arabica",
    packaging: "Bolsas",
    packagingSize: "1 kg",
    specifications: [
      { label: "Variedad", value: "Arábica" },
      { label: "Altitud", value: "+ 1000 metros" },
      { label: "Denominación", value: "De origen protegida" },
      { label: "Notas", value: "Chocolate, caramelo" },
    ],
  },
  {
    id: 12,
    name: "Café Robusta Premium",
    category: "Café",
    producer: "Finca El Paraíso",
    vendorId: "vendor_012",
    location: "Santa Ana, El Salvador",
    country: "El Salvador",
    description: "Café robusta premium, cuerpo fuerte y aromático",
    fullDescription:
      "Café robusta premium con cuerpo fuerte, notas de nuez y especias. Excelente para mezclas y espressos. Procesado bajo estrictos estándares de calidad.",
    price: "$3.50/kg",
    minOrder: "100 kg",
    rating: 4.7,
    reviews: 156,
    image: "/cafe-robusta-premium-grano.jpg",
    verified: true,
    slug: "cafe-robusta",
    packaging: "Bolsas",
    packagingSize: "1 kg",
    specifications: [
      { label: "Variedad", value: "Robusta" },
      { label: "Origen", value: "Santa Ana, El Salvador" },
      { label: "Cuerpo", value: "Fuerte" },
      { label: "Notas", value: "Nuez, especias" },
    ],
  },
  {
    id: 13,
    name: "Cacao en Grano Fermentado",
    category: "Cacao",
    producer: "Chocolatería Artesanal",
    vendorId: "vendor_013",
    location: "Izalco, El Salvador",
    country: "El Salvador",
    description: "Cacao fermentado y seco, sabor intenso",
    fullDescription:
      "Cacao fino de aroma fermentado y seco bajo técnicas tradicionales. Sabor intenso con notas de frutas y flores. Ideal para chocolate artesanal de alta calidad.",
    price: "$6.50/kg",
    minOrder: "25 kg",
    rating: 4.9,
    reviews: 201,
    image: "/cacao-grano-sacos-fermentado.jpg",
    verified: true,
    slug: "cacao-fermentado",
    packaging: "Sacos",
    packagingSize: "60 kg",
    specifications: [
      { label: "Tipo", value: "Fino de aroma" },
      { label: "Origen", value: "Izalco, El Salvador" },
      { label: "Proceso", value: "Fermentado tradicional" },
      { label: "Notas", value: "Frutas, flores" },
    ],
  },
  {
    id: 14,
    name: "Semillas de Maíz Certificadas",
    category: "Semillas",
    producer: "Semillas Mejoradas SV",
    vendorId: "vendor_014",
    location: "Ahuachapán, El Salvador",
    country: "El Salvador",
    description: "Semillas certificadas de alto rendimiento, germancia 95%",
    fullDescription:
      "Semillas de maíz mejoradas y certificadas con germancia mínima del 95%. Alto rendimiento en variedad de climas y suelos. Tratadas contra plagas de almacén.",
    price: "$2.20/kg",
    minOrder: "100 kg",
    rating: 4.8,
    reviews: 93,
    image: "/semillas-maiz-certificadas-agricultura.jpg",
    verified: true,
    slug: "semillas-maiz",
    packaging: "Sacos",
    packagingSize: "25 kg",
    specifications: [
      { label: "Certificación", value: "Oficial" },
      { label: "Origen", value: "Ahuachapán, El Salvador" },
      { label: "Germancia", value: "95% mínimo" },
      { label: "Tratamiento", value: "Antihongos y plagas" },
    ],
  },
  {
    id: 15,
    name: "Semillas de Soya Transgénica",
    category: "Semillas",
    producer: "Innovación Agrícola",
    vendorId: "vendor_015",
    location: "San Salvador, El Salvador",
    country: "El Salvador",
    description: "Semillas de soya transgénica resistentes a plagas",
    fullDescription:
      "Semillas de soya transgénica de última generación, resistentes a plagas y enfermedades. Alto rendimiento, adaptadas a diferentes climas. Germancia garantizada del 95%.",
    price: "$1.20/kg",
    minOrder: "500 kg",
    rating: 4.6,
    reviews: 112,
    image: "/semillas-soya-transgenicas-sacos.jpg",
    verified: true,
    slug: "semillas-soya",
    packaging: "Sacos",
    packagingSize: "50 kg",
    specifications: [
      { label: "Tipo", value: "Transgénica" },
      { label: "Origen", value: "San Salvador, El Salvador" },
      { label: "Resistencia", value: "Plagas y enfermedades" },
      { label: "Germancia", value: "95% garantizada" },
    ],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((product) => product.slug === slug)
}

export function getProductById(id: number): Product | undefined {
  return allProducts.find((product) => product.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return allProducts.filter((product) => product.category === category)
}
